version: "2"

services:
  dist-serve:
     build:
         context: ./
         dockerfile: Dockerfile
     container_name: bims-angular
     working_dir: /home/node/app
     volumes:
       - .:/home/node/app
     environment:
         - NODE_ENV=development
     expose:
         - "8081"
         - "80"
     ports:
       - 80:80
     tty: true
     restart: always